Fixes are fixes.. right?
BBN-Holding/bbn.one pull request #24
Opened 2024-11-01 14:36 UTC by upayanmazumder

## Updates

### Fixed unclickable footer

#### Z-index issue

![image](https://github.com/user-attachments/assets/0f096aec-47a2-4bac-8af4-c40bcef958f2)

### Removed broken links (facebook and blog)
 
#### Facebook ![image](https://github.com/user-attachments/assets/957b528f-314d-455e-81a5-ee5089bbcf02)

#### Blog ![image](https://github.com/user-attachments/assets/15b3b5f0-a120-4598-b182-4827ac6252f2)

### Button Redesign Update

#### Previous Design

![Old Button Design](https://github.com/user-attachments/assets/d398375e-b96b-442a-a903-afed3846b9a0)

#### New Design

![New Button Design](https://github.com/user-attachments/assets/7a0c246e-10c4-4349-9980-3400c1ba5c0a)

2024-11-01 14:40 UTC, lucsoft requested changes

2024-11-01 14:40 UTC, lucsoft commented on pages/shared/footer.css
> +    z-index: 10;
move this to the .icon-bar

2024-11-01 14:40 UTC, lucsoft commented on pages/shared/footer.ts
> -                            ["facebook", "Facebook", "https://www.facebook.com/bbn.holding/"],
instead of removing can you replace it with the Mastodon page?

2024-11-01 14:42 UTC, upayanmazumder commented on pages/shared/footer.ts
> -                            ["facebook", "Facebook", "https://www.facebook.com/bbn.holding/"],
what mastodon page bruh

2024-11-01 14:43 UTC, upayanmazumder commented on pages/shared/footer.ts
> -                            ["facebook", "Facebook", "https://www.facebook.com/bbn.holding/"],
![image](https://github.com/user-attachments/assets/898e7a43-ad83-447d-9f3c-3327a2d290cb)
bro created it a week back hmm

2024-11-01 14:52 UTC, upayanmazumder commented on pages/shared/footer.ts
> -                            ["facebook", "Facebook", "https://www.facebook.com/bbn.holding/"],
![Uploading image.png…]()

2024-11-01 14:56 UTC, upayanmazumder commented
> NOTE TO SELF : First finalise your commits

2024-11-02 14:30 UTC, upayanmazumder commented
merge..?

2024-11-02 14:31 UTC, greg6775 commented
there's no need to remove the dead links at this point. solution for this would be to start the blog container again etc

2024-11-02 14:33 UTC, greg6775 commented
furthermore, we're already working on revising all legal pages. the modified code has already been removed in the updated version (not on prod yet)

2024-11-02 14:33 UTC, closed without merging

2024-11-06 09:12 UTC, upayanmazumder commented
okkk